# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example

end

target 'SelfUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SelfUI
  pod 'GoogleMLKit/FaceDetection'

  target 'SelfUITests' do
    # Pods for testing
  end

end
